# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b4c20d3d32257dfc7a0a80e9793514019dab7863166d3ceeda2049aa2afa60e52a598863e04bec535edcaee9bca7b3eaf8be0b3e451a73c9927ce7147c7983

test:
  secret_key_base: 8c1b7b7bc059372f9404c7f9400ac6a11c0c23bbf70c97a1dedce972518a3996148a284816d62bd09f85e570a010ef3a4d30c3b69e52b7f556a2197f0e5e2565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
